from typing import Callable, Protocol, TypeVar

from P4PCore.abstract.IncludeGC import IncludeGC

T = TypeVar("T")
K = TypeVar("K")
V = TypeVar("V")

class Manager(Protocol):
    pass

class SetManager(Manager, Protocol[T]):
    async def add(self, item:T) -> bool: ... # return !contains
    async def remove(self, item:T) -> bool: ...
    async def contains(self, item:T) -> bool: ...
    async def clear(self) -> None: ...
    async def getAll(self) -> set[T]: ...

class ListManager(Manager, Protocol[V]):
    async def insertNext(self, value:V, index:int=-1) -> None: ...
    async def change(self, index:int, value:V) -> None: ...
    async def get(self, index:int) -> V | None: ...
    async def getLength(self) -> int: ...
    async def getIndex(self, value:V) -> int: ...
    async def getAll(self) -> list[V]: ...
    async def delete(self, index:int) -> None: ...
    async def pop(self, index:int) -> V: ...
    async def deleteValue(self, value:V) -> None: ...
    async def clear(self) -> None: ...

class ReadableKV(Protocol[K, V]):
    async def get(self, key:K) -> V | None: ...
    async def getAll(self) -> dict[K, V]: ...
    async def size(self) -> int: ...
class ReadableBiKV(ReadableKV, Protocol[K, V]):
    async def getKey(self, value:V) -> K: ...
class WriteableKV(Protocol[K, V]):
    async def put(self, key:K, value:V) -> V | None: ...
class AddableKV(Protocol[K, V]):
    async def add(self, key:K, value:V) -> bool: ... # return !contains or contains and already set to the same value
class AddableBiKV(Protocol[K, V]):
    async def add(self, key:K, value:V) -> bool: ... # return !contains or contains and already set to the same key-value
class DeletableKV(Protocol[K, V]):
    async def delete(self, key:K) -> bool: ...
    async def clear(self) -> None: ...
class DeletableBiKV(DeletableKV, Protocol[K, V]):
    async def deleteByValue(self, value:V) -> bool: ...

class CannotOverwriteKVManager(Manager, Protocol[K, V]):
    async def add(self, *key:K, value:V) -> bool: ... # return !contains or contains and already set to the same value
    async def delete(self, key:K) -> bool: ...
    async def get(self, key:K) -> V | None: ...
    async def getAll(self) -> dict[K, V]: ...
    async def clear(self) -> None: ...

class CannotDeleteKVManager(Manager, Protocol[K, V]):
    async def put(self, key:K, value:V) -> V | None: ...
    async def get(self, key:K) -> V | None: ...
    async def getAll(self) -> dict[K, V]: ...


class CannotDeleteAndOverwriteKVManager(Manager, Protocol[K, V]):
    async def add(self, *key:K, value:V) -> bool: ... # return !contains or contains and already set to the same value
    async def get(self, key:K) -> V | None: ...
    async def getAll(self) -> dict[K, V]: ...

class CannotDeleteAndOverwriteAndReversedLookupPossibleKVManager(Manager, Protocol[K, V]):
    async def add(self, *key:K, value:V) -> bool: ... # return !contains or contains and already set to the same key-value
    async def get(self, key:K) -> V | None: ...
    async def getKey(self, value:V) -> K | None: ...
    async def getAll(self) -> dict[K, V]: ...

class CannotDeleteAndSetValuedKVManager(Manager, Protocol[K, V]):
    async def addKey(self, key:K) -> bool: ... # return !contains
    async def addValue(self, key:K, value:V) -> bool: ... # return contains
    async def get(self, key:K) -> set[V] | None: ...
    async def getAll(self) -> dict[K, set[V]]: ...

class AmountLimitedTokenManager(Manager, Protocol[T]):
    async def waitAndAllocate(self, timeoutMilliSec:int | None=None) -> T | None: ...
    async def release(self, token:T) -> None: ...