# This file is editable for custom configurations

DB_FILE = "P4P.db"

GET_I_AM_FUNC_NAME = "getIAm"
GET_SORTED_NODES_FUNC_NAME = "getSortedNodes"

MAX_NODES = 100
MAX_NODES_MARGIN = 15

NODES_LIMIT_FOR_GET = 9

MESSAGE_CONTENT_LIMIT = 900
MESSAGE_LIST_LIMIT = 100
MESSAGES_LIMIT_FOR_GET = 5

MESSAGE_LIFE_SEC = 60*60*24

CHANCE_FOR_SEND_REPLY_MESSAGE = 1/5