# This file is editable for custom configurations

TIME_OUT_MILLI_SEC = 250
WAITING_RESPONSES_GC_SECS = TIME_OUT_MILLI_SEC*2
PING_WINDOW = 17
PING_MILLI_SEC_REDUNDANCIES = [
    (20, 2),
    (80, 4),
    (150, 8),
    (1000, 10),
]
PING_CALC_TRIM_RATIO = 0.12

class SyncIntervalSec:
    GOSSIP = 0.5

MAX_GOSSIP_NODES_FOR_SEND = 4
MAX_GOSSIP_NODE_LIST = 400
TTL_GOSSIP_NODE = 2

SAVED_PATH = "saved/"