# This file is editable for custom configurations

NET_SEMAPHORE = 100

TIME_OUT_SEC = 1.5
PING_WINDOW = 17
PING_MILLI_SECS_REDUNDANCIES = [
    (20, 2),
    (80, 4),
    (150, 8),
    (1000, 10),
]
PING_CALC_TRIM_RATIO = 0.12

SAVED_DIR_PATH = "saved/"
STARTED_FILE_NAME = "started"

HELLO_SEND_VOLUME = 3
ENCRYPTER_OTHER_PARTY_SEQ_WINDOW = 10