from enum import IntEnum

ENDIAN = "big"

MAGIC = b"P4P"

PROTOCOL_VER = 4

MAGIC += PROTOCOL_VER.to_bytes(4, ENDIAN)

SOCKET_BUFFER = 1400
STR_ENCODING = "utf-8"

ANY_UNIQUE_RANDOM_BYTES_SIZE = 16
ANY_SECRET_SIZE = 32

AESGCM_KEY_BIT_SIZE = 256
AESGCM_NONCE_SIZE = 12 # The first bit of the nonce is true(1) if the nonce is generated by the first node to hello, and false(0) if generated by the node to recv hello.
# Make sure to that.

X25519_DERIVE_KEY_INFO = b"X25519_DERIVE_KEY"
X25519S_SHARED_SECRET_AND_AES_KEY_INFO = b"X25519S_SHARED_SECRET-AESGCM_KEY"
MULTIPLE_PEOPLES_SHARED_SECRET_AND_AES_INFO_BASE = b"MULTIPLE_PEOPLES_SHARED_SECRET-AES_INFO"

class PacketElementSize:
    MAGIC=len(MAGIC)
    RESPONSE_IDENTIFY=ANY_UNIQUE_RANDOM_BYTES_SIZE
    PACKET_FLAG=1
    MODE_FLAG=1
    SEQ=8

SEQ_MAX_BY_PACKET_ELEMENT_SIZE = (1 << PacketElementSize.SEQ*8)-1

class SecurePacketElementSize(PacketElementSize):
    PROTOCOL_CLIENT=2
    PROTOCOL_VER=4
    ED25519_PUBLIC_KEY=32
    ED25519_SIGN=64
    X25519_PUBLIC_KEY=32
    AES_SALT=ANY_UNIQUE_RANDOM_BYTES_SIZE
    CONTENT_UUID=16

class PacketFlag(IntEnum):
    PINGPONG = 1
    SECURE = 2

class ModeFlag(IntEnum):
    PING = 1
    PONG = 2

    HELLO = 10
    RESP_HELLO = 11
    SECOND_HELLO = 12
    MAIN_DATA = 13

def getMaxDataSizeOnAesEncrypted() -> int:
    return ((
        SOCKET_BUFFER
        - SecurePacketElementSize.MAGIC
        - SecurePacketElementSize.PACKET_FLAG
        - SecurePacketElementSize.MODE_FLAG
        - SecurePacketElementSize.SEQ
    ) // 16) * 16