from enum import IntEnum

ENDIAN = "big"

MAGIC = b"P4P"

PROTOCOL_VER = 2

MAGIC += PROTOCOL_VER.to_bytes(4, ENDIAN)

SOCKET_BUFFER = 1400
STR_ENCODING = "utf-8"

REDUNDANCY = 3

RELIABLE_PACKETS_PER_CHUNK = 30
"""
    RELIABLE_PACKETS_PER_CHUNK <= (
        SOCKET_BUFFER
        -ReliablePacketElementSize.PACKET_FLAG
        -ReliablePacketElementSize.PACKET_MODE_FLAG
        -ReliablePacketElementSize.SESSION_ID
        -ReliablePacketElementSize.ED25519_SIGN
    ) // ReliablePacketElementSize.SEQ_AND_CHUNK_COUNT
"""

ANY_UNIQUE_RANDOM_BYTES_SIZE = 16
ANY_SECRET_SIZE = 32

AESGCM_KEY_BIT_SIZE = 256
AESGCM_NONCE_SIZE = 12 # The first bit of the nonce is true(1) if the nonce is generated by the first node to hello, and false(0) if generated by the node to recv hello.
# Make sure to that.

XXHASH_BIT_SIZE = 64

X25519_DERIVE_KEY_INFO = b"X25519_DERIVE_KEY"
X25519S_SHARED_SECRET_AND_AES_KEY_INFO = b"X25519S_SHARED_SECRET-AESGCM_KEY"
MULTIPLE_PEOPLES_SHARED_SECRET_AND_AES_INFO_BASE = b"MULTIPLE_PEOPLES_SHARED_SECRET-AES_INFO"

class PacketElementSize:
    MAGIC=len(MAGIC)
    XXHASH_MODE_FLAG=1
    RESPONSE_TOKEN=ANY_UNIQUE_RANDOM_BYTES_SIZE
    PACKET_FLAG=1
    MODE_FLAG=1
    SEQ=8
    XXHASH = XXHASH_BIT_SIZE//8

SEQ_MAX_BY_PACKET_ELEMENT_SIZE = (1 << PacketElementSize.SEQ*8)-1

class SecurePacketElementSize(PacketElementSize):
    PROTOCOL_CLIENT=2
    PROTOCOL_VER=4
    ED25519_PUBLIC_KEY=32
    ED25519_SIGN=64
    X25519_PUBLIC_KEY=32
    AES_SALT=ANY_UNIQUE_RANDOM_BYTES_SIZE
    CONTENT_TYPE_UUID=16

class PacketFlag(IntEnum):
    EX = 1
    SECURE = 2

class PacketModeFlag(IntEnum):
    PING = 1
    PONG = 2
    HELLO = 10
    RESP_HELLO = 11
    SECOND_HELLO = 12
    MAIN_DATA = 13

def getMaxDataSizeOnAesEncrypted(enableXxhashMode:bool=False) -> int:
    return ((
        SOCKET_BUFFER
        - SecurePacketElementSize.XXHASH_MODE_FLAG
        - SecurePacketElementSize.MAGIC
        - SecurePacketElementSize.PACKET_FLAG
        - SecurePacketElementSize.MODE_FLAG
        - (SecurePacketElementSize.XXHASH if enableXxhashMode else 0)
        - SecurePacketElementSize.SEQ
    ) // 16) * 16

print(((
        SOCKET_BUFFER
        - SecurePacketElementSize.XXHASH_MODE_FLAG
        - SecurePacketElementSize.MAGIC
        - SecurePacketElementSize.PACKET_FLAG
        - SecurePacketElementSize.MODE_FLAG
        - 0
        - SecurePacketElementSize.SEQ
    ) // 16) * 16)